// redux/counter/constants.js
export const PREFIX = "COUNTER";

export const INCREMENT = `${PREFIX}/INCREMENT`;
export const DECREMENT = `${PREFIX}/DECREMENT`;

export const INCREMENT_BY = `${PREFIX}/INCREMENT_BY`;
export const DECREMENT_BY = `${PREFIX}/DECREMENT_BY`;

export const INCREMENT_BY_ASYNC_REQUEST = `${PREFIX}/INCREMENT_BY_ASYNC_REQUEST`;
export const INCREMENT_BY_ASYNC_SUCCESS = `${PREFIX}/INCREMENT_BY_ASYNC_SUCCESS`;
export const INCREMENT_BY_ASYNC_FAILURE = `${PREFIX}/INCREMENT_BY_ASYNC_FAILURE`;
